import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr';
import { VersionResponseData } from '../src/types';

const fetcher = (url: string) => fetch(url).then(res => res.json())

export default function Home() {
  const {data, error} = useSWR<VersionResponseData>('/api/version', fetcher);

  return (
    <div className={styles.container}>
      <Head>
        <title>John Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Deployed
        </h1>
        <br />
        <br />
        <code className={styles.code}>
          {error ? String(error) : (data?.version ?? 'no version')}
        </code>
      </main>
    </div>
  )
}
